In [ ]:
# To covert different units of measurement

In [16]:
def convert_length(value, unit):
    if unit == 'm':
        return value * 3.28084
    elif unit == 'ft':
        return value / 3.28048
    else:
        raise ValueError("Invalid Length Unit")

def convert_weight(value, unit):
    if unit == "kg":
        return value * 2.20462
    elif unit == "pound":
        return value / 2.2063
    else:
        raise ValueError("Invalid Weight Unit")
        
def convert_volume(value, unit):
    if unit == "l":
        return value * 0.264172
    elif unit == "gal":
        return value /  0.264172
    else:
        raise ValueError("Invalid Volume Unit")


def main ():
    print ("Unit Converter")
    print("1. Length (Meters to Feet / Feet to Meters)")
    print("2. Weight (Kilograms to Pounds / Pounds to Kilograms)")
    print("3. Volume (Liters to Gallons / Gallons to Liters)")


    try:
        choice = int(input("Choose the conversion type 1/2/3: "))
        value = float(input("Enter the value to convert"))

        if choice == 1:
             choice = input("Enter the unit(m for meters, ft for feet): ").strip().lower()
             result = convert_length(value,choice)
             print(f"Result : {result:.2f}")
        elif choice == 2:
            unit = input("Enter unit (kg for kilograms, lbs for pounds): ").strip().lower()
            result = convert_weight(value, unit)
            print(f"Converted Value: {result:.2f}")
        elif choice == 3:
            unit = input("Enter unit (L for liters, gal for gallons): ").strip().lower()
            result = convert_volume(value, unit)
            print(f"Converted Value: {result:.2f}")
        else:
            print("Invalid choice. Please select a valid option.")
    except ValueError as e:
          print(f"Error: {e}")

if __name__ == "__main__":
    main()


        



Unit Converter
1. Length (Meters to Feet / Feet to Meters)
2. Weight (Kilograms to Pounds / Pounds to Kilograms)
3. Volume (Liters to Gallons / Gallons to Liters)


Choose the conversion type 1/2/3:  2
Enter the value to convert 66
Enter unit (kg for kilograms, lbs for pounds):  kg


Converted Value: 145.50


In [ ]:
 # Perform various mathematical operations on a list of numbers.

In [18]:
def calculate_sum(numbers):
    return sum(numbers)

def calculate_average(numbers):
    if not numbers:
        raise ValueError("Cannot calculate average of an empty list.")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    if not numbers:
        raise ValueError("Cannot find maximum of an empty list.")
    return max(numbers)

def find_minimum(numbers):
    if not numbers:
        raise ValueError("Cannot find minimum of an empty list.")
    return min(numbers)

def main():
    try:
        print("Choose the type of operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")
        
        operation = int(input("Choose the operation (1,2,3,4): "))
        numbers = list(map(float, input("Enter the list of numbers separated by spaces: ").strip().split()))
        
        operations = {
            1: calculate_sum,
            2: calculate_average,
            3: find_maximum,
            4: find_minimum
        }
        
        if operation in operations:
            result = operations[operation](numbers)
            print(f"Result: {result}")
        else:
            print("Invalid choice. Please select a valid option.")
    
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Choose the type of operation:
1. Sum
2. Average
3. Maximum
4. Minimum


Choose the operation (1,2,3,4):  4
Enter the list of numbers separated by spaces:  2 8 9 5 4 7


Result: 2.0


In [ ]:
# Extracts every other elements from a list

In [22]:
def extract_every_other(lst):
    return lst[::2]
    
def main():
    lst= [2,3,4,5,6,7,8,9,10]
    result = extract_every_other(lst)
    print(result)

main()

[2, 4, 6, 8, 10]


In [ ]:
#Slice a Subset

In [31]:
 def get_sublist(lst, start,end):
     return lst[start:end]

def main():
    lst = [1,2,3,4,5,6,7,8,9,10]
    start = 3
    end = 9
    print(get_sublist(lst, start,end))

main()

[4, 5, 6, 7, 8, 9]


In [ ]:
#Reverse the list string

In [6]:
def reverse_list(lst):
    return lst [::-1]

def main():
    lst = [1,2,3,4,5]
    print(reverse_list(lst))

main()
    

[5, 4, 3, 2, 1]


In [ ]:
#Remove the First and Last Elements:

In [24]:
def remove_first_last(lst):
    return lst[1:-1]

def main():
    lst = [4,1,2,3,4,5,6,7,8,9,10,11]        
    print(remove_first_last(lst))

main()
    

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
#Get the First n Elements:

In [32]:
def get_first_n(lst,n):
    
    return lst[:n]

def main():
    lst = [4,1,2,3,4,5,6,7,8,9,10,11]
    print(lst)
    n = int(input("Enter the number of elements you want to extract: "))
    get_first_n(lst,n)
    print (get_first_n(lst,n))

main()

[4, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


Enter the number of elements you want to extract:  2


[4, 1]


In [ ]:
# Extract Elements from the End:

In [63]:
def get_last_n(lst,n):
    
    return lst[-n:]

def main():
    lst = [1,2,3,4,5,6,7,8,9,10,11]
    print(lst)
    n = int(input("Enter the number of elements you want to extract: "))
    get_last_n(lst,n)
    print (get_last_n(lst,n))

main()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


Enter the number of elements you want to extract:  5


[7, 8, 9, 10, 11]


In [ ]:
# Extract Elements in Reverse Order:

In [77]:
def  reverse_skip(lst):
    return lst[-2::-2]

def main():
    lst = [1,2,3,4,5,6,7,8]
    print(reverse_skip(lst))

main()

[7, 5, 3, 1]


In [ ]:
# Nested List

In [97]:
def flatten(lst):
    return [item for sublist in lst for item in sublist]

def main():
    lst = [[1,2,3], [4,5], [7]]
    print(flatten(lst))

main()



[1, 2, 3, 4, 5, 7]


In [99]:
# Accessing Nested List Elements:

In [101]:
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

def main():
    lst = [[1,2,3], [4,5,6],[7,8,9]]
    indices = [2,2]
    print(access_nested_element(lst, indices))

main()

9


In [ ]:
# Sum of All Elements in a Nested List

In [16]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def main():
    lst = [[1,2],[3,[4,5]], 6]
    print(sum_nested(lst))
main()

21


In [ ]:
# Remove Specific Element from a Nested List:

In [8]:
def remove_element(lst, element):
    result = []
    for item in lst:
        if isinstance(item, list):
            cleaned_list = remove_element(item, element)
            if cleaned_list:
                result.append(cleaned_list)
        elif item != element:
            result.append(item)
    return result

    
def main():
    lst = [[1,2], [3,2], [4,5]]
    element = 2
    print(remove_element(lst, element))

main()
    

[[1], [3], [4, 5]]


In [ ]:
# Find the Maximum Element in a Nested List:

In [20]:
def find_max(lst):
    max_value = float('-inf') 
    
    for item in lst:
        if isinstance(item, list):  
            max_value = max(max_value, find_max(item))
        else: 
            max_value = max(max_value, item)
    
    return max_value

nested_list = [[1, 2], [3, [4, 5]], 6]
print(find_max(nested_list))  


6


In [ ]:
# Count Occurrences of an Element in a Nested List:

In [ ]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deef_flatten(item))
        else:
            result.append(item)
    
def main():
    lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
    

In [ ]:
# Nested List Average:

In [28]:
def average_nested(lst):
    total = 0
    length = len(lst)
    for item in lst:
        if isinstance(item, list):
            total += average_nested(item)
        else:
            total += item
    average = total/length
    return average

def main():
    lst = [[1,2],[3,4],[5, 6]]
    print(average_nested(lst))
main()

3.5


In [ ]:
NUMPY - OPERATIONS

In [ ]:
# Initialize an empty array with size 2X2.
# 2. Initialize an all one array with size 4X2.
# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [32]:
import numpy as np
empty_array = np.empty((2,2))
print("Empty Array:\n", empty_array)








Empty Array:
 [[2.12199579e-314 6.95165821e-310]
 [6.79834329e-321 1.08433985e-311]]


In [36]:
import numpy as np

one_array = np.ones((4,2))
print("\nAll Ones Array:\n", one_array)




All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [38]:
import numpy as np

value = 7
full_array= np.full((2,2),7)
print("\nFilled Array:\n", full_array)


Filled Array:
 [[7 7]
 [7 7]]


In [46]:
array = np.array ([[1,2,3], [7, 8, 9]])
zeros_like_array = np.zeros_like (array)
print("\nZeros Like Array:\n", zeros_like_array)

ones_like_array = np.ones_like(array)
print("\nOnes Like Array:\n", ones_like_array)

new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)




Zeros Like Array:
 [[0 0 0]
 [0 0 0]]

Ones Like Array:
 [[1 1 1]
 [1 1 1]]

Converted NumPy Array:
 [1 2 3 4]


In [ ]:
# Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
# Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
# 2. Create a 3X3 matrix with values ranging from 0 to 8.
# {Hint:look for np.reshape()}
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
# 4. Create a random array of size 30 and find the mean of the array.
# {Hint:check for np.random.random() and array.mean() function}
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
# 6. Create a zero array of size 10 and replace 5th element with 1.
# 7. Reverse an array arr = [1,2,0,0,4,0].
# 8. Create a 2d array with 1 on border and 0 inside.
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [104]:
import numpy as np
a = np.arange(10,50)
print("Array from 10 to 49:\n", a)

b = np.arange(9).reshape(3,3)
print("\n3x3 Matrix:\n",b)

c = np.eye(3)
print("\n3x3 Identity Matrix:\n",c)

d= np.random.random(30)
mean_value = d.mean()
print("\n",d)
print("The mean value is:\n ",mean_value)

e = np.random.random((10,10))
print("The min value is\n ", e.min())
print("The min value is\n ", e.max())

f = np.zeros(10)
f[4] = 1
print(f)

arr = [1,2,0,0,4,0]
print("The reverse array is\n: ", arr[::-1])

border_array = np.ones((5,5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with Border 1 and Inside 0:\n", border_array)

checkboard = np.zeros((8,8))
checkboard[1::2, ::2]=1
checkboard[::2, 1::2]= 1
print("\n8x8 Checkerboard Pattern:\n", checkboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [0.11333306 0.19157987 0.99009343 0.65515852 0.87646467 0.80101033
 0.68094611 0.63640884 0.60411256 0.12506437 0.66803096 0.8872679
 0.24840357 0.5881455  0.67261135 0.95208014 0.35923878 0.76326517
 0.84514365 0.84913222 0.7810113  0.29058886 0.14691956 0.88818637
 0.98927327 0.6800591  0.56278715 0.55762622 0.93625115 0.85982235]
The mean value is:
  0.6400005448240405
The min value is
  0.005648946804197474
The min value is
  0.9999651118128078
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
The reverse array is
:  [0, 4, 0, 0, 2, 1]

2D Array with Border 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 

In [110]:
# Problem - 3: Array Operations:
# For the following arrays:
# x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
# v = np.array([9,10]) and w = np.array([11,12]);
# Complete all the task using numpy:
# 1. Add the two array.
# 2. Subtract the two array.
# 3. Multiply the array with any integers of your choice.
# 4. Find the square of each element of the array.
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
# # 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [144]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) 
w = np.array([11,12]);

add = x+y
print("\nAddition \n", add)

sub = x-y
print("\nSubtraction \n", sub)

multiply = x * 5
print("\nMultiplication \n", multiply)

print("\n The square of x is\n", np.square(x))
print("\n The square of y is\n", np.square(y))
print("\n The square of v is\n", np.square(v))
print("\n The square of w is\n", np.square(w))

dot_vw = np.dot(v,w)
dot_xv = np.dot(x, v) 
dot_xy = np.dot(x, y)
print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

concat_xy_row = np.concatenate((x,y), axis=0)
concat_vw_col = np.concatenate((v,w))
print("\nConcatenation of x and y along rows:\n", concat_xy_row)
print("\nConcatenation of v and w along columns:\n", concat_vw_col)

print("\nConcactenate of x and v raises an error because x is 2D matrix with size 2*2 and v is 1D array with size 2.Since their shapes do not match, NumPy raises a ValueError")





Addition 
 [[ 6  8]
 [10 13]]

Subtraction 
 [[-4 -4]
 [-4 -3]]

Multiplication 
 [[ 5 10]
 [15 25]]

 The square of x is
 [[ 1  4]
 [ 9 25]]

 The square of y is
 [[25 36]
 [49 64]]

 The square of v is
 [ 81 100]

 The square of w is
 [121 144]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [ 9 10 11 12]

Concactenate of x and v raises an error because x is 2D matrix with size 2*2 and v is 1D array with size 2.Since their shapes do not match, NumPy raises a ValueError


In [ ]:
# • For the following arrays:
# A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:
# 1. Prove A.A−1 = I.
# 2. Prove AB ̸= BA.
# 3. Prove (AB)T = BTAT

In [150]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inv = np.linalg.inv(A)
identity = np.dot (A, A_inv)
print("A * A_inv = I:\n", np.round(identity))


AB = np.dot(A,B)
print("\nAB:\n", AB)
BA = np.dot (B,A)
print("\nBA:\n", BA)
check = np.array_equal(AB, BA)
print("\nIs AB == BA?", check)  

AB_transpose = np.transpose(AB)
print("\n(AB)ᵀ:\n", AB_transpose)
BT_AT = np.dot(np.transpose(B), np.transpose(A)) 
print("\nBᵀ Aᵀ:\n", BT_AT)
transpose_check = np.array_equal(AB_transpose, BT_AT) 



A * A_inv = I:
 [[1. 0.]
 [0. 1.]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Is AB == BA? False

(AB)ᵀ:
 [[23 51]
 [13 29]]

Bᵀ Aᵀ:
 [[23 51]
 [13 29]]


In [ ]:
# Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

In [156]:
import numpy as np
A = np.array([[2,-3,1],
             [1, -1, 2],
             [3,1,-1]
             ])

B = np.array ([-1,-3,9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution for x, y, z:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

Solution for x, y, z:
x = 1.9999999999999998
y = 1.0000000000000004
z = -1.9999999999999996


In [ ]:
# 1. Element-wise Addition:
# • Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
# and Print the time taken for this operation.
# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
# this operation.

In [165]:
import numpy as np
import time

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

#using Python
start_time = time.time()
result_list= [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("Python List Addition Time:", end_time - start_time)

# using NUmpy Array
array1 = np.arange(size)
array2 = np.arange(size)
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print("NumPy Array Addition Time:", end_time - start_time)


Python List Addition Time: 0.3300364017486572
NumPy Array Addition Time: 0.0


In [ ]:
# 2. Element-wise Multiplication
# • Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
# Measure and Print the time taken for this operation.
# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
# this operation.

In [169]:
# Using Python lists
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print("Python List Multiplication Time:", end_time - start_time)

# Using NumPy arrays    
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
print("NumPy Array Multiplication Time:", end_time - start_time)
      

Python List Multiplication Time: 0.33768153190612793
NumPy Array Multiplication Time: 0.0040378570556640625


In [171]:
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print("Python List Dot Product Time:", end_time - start_time)

# Using NumPy arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print("NumPy Array Dot Product Time:", end_time - start_time)

Python List Dot Product Time: 0.4141511917114258
NumPy Array Dot Product Time: 0.0024940967559814453


In [ ]:
matrix_size = 1000

# Using Python lists
matrix1 = [[i for i in range(matrix_size)] for j in range(matrix_size)]
matrix2 = [[i for i in range(matrix_size)] for j in range(matrix_size)]

start_time = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)] for i in range(matrix_size)]
end_time = time.time()
print("Python List Matrix Multiplication Time:", end_time - start_time)


# Using NumPy arrays
matrix1_np = np.arange(matrix_size * matrix_size).reshape(matrix_size, matrix_size)
matrix2_np = np.arange(matrix_size * matrix_size).reshape(matrix_size, matrix_size)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print("NumPy Array Matrix Multiplication Time:", end_time - start_time)
